{{- if .Values.kubearmorRelay.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: kubearmor
  namespace: {{.Release.Namespace}}
  labels:
    kubearmor-app: kubearmor-relay
spec:
  ports:
  - port: 32767
    protocol: TCP
    targetPort: 32767
  selector:
    kubearmor-app: kubearmor-relay
{{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.kubearmorController.name }}-webhook-service
  namespace: {{.Release.Namespace}}
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 9443
  selector:
    kubearmor-app: {{ .Values.kubearmorController.name }}
